[package]
name = "set-1"
version = "0.1.0"
authors = ["Ray Xu <megrxu@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex-literal = "0.2.2"
hex = "*"
lazy_static = "1.4.0"
base64 = "*"
eva-crypto = "*"
