[package]
name = "set-2"
version = "0.1.0"
authors = ["Ray Xu <megrxu@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eva-crypto = "*"
set-1 = {path="../set-1/"}
rand = "0.8.5"
